artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/MortezaLayegh/data/raw/main/H_B_merged_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/merged_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/merged_data.csv
  preprocessor_obj_file_path: 'artifacts/data_transformation/preprocessor.joblib'




model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_df.csv
  test_data_path: artifacts/data_transformation/test_df.csv
  #preprocessor_obj_file_path: 'artifacts/data_transformation/preprocessor.joblib'
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test_df.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json


